### ISSUE TITLE
Question regarding Cross-Graph/gae

### ISSUE THREAD

**Issue by zixiaoshuixin** [FakeTibbers/Cross-Graph#1]
Hi,

I got an error message when I reproduced your project named "Cross-Graph" and could you please tell how to solve it. Thank you so much!

When I run train.py, the error occurred.

It seems that the line 145 of train.py, "roc_auc_score(labels_all, preds_all)" function passed in the arguments "labels_all" and "preds_all" contain NaN values. So the error message is "ValueError: Input contains NaN, infinity or a value too large for dtype('float64')."

The  error message in console is as follows：
Traceback (most recent call last):
  File "/home/gpu/sunqin/gae/train.py", line 265, in <module>
    roc_curr1, ap_curr1 = get_roc_score(val_edges, val_edges_false, emb=sess.run(GCN1.z_mean, feed_dict=feed_dict))
  File "/home/gpu/sunqin/gae/train.py", line 159, in get_roc_score
    roc_score = roc_auc_score(labels_all, preds_all)
  File "/etc/anaconda3/envs/sunqin/lib/python3.9/site-packages/sklearn/metrics/_ranking.py", line 546, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "/etc/anaconda3/envs/sunqin/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/etc/anaconda3/envs/sunqin/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by yzfxmu** [comment]
I can run the demo well. Maybe the version of your package is too new.

**Comment by yzfxmu** [comment]
> Hi,
> 
> I got an error message when I reproduced your project named "Cross-Graph" and could you please tell how to solve it. Thank you so much!
> 
> When I run train.py, the error occurred.
> 
> It seems that the line 145 of train.py, "roc_auc_score(labels_all, preds_all)" function passed in the arguments "labels_all" and "preds_all" contain NaN values. So the error message is "ValueError: Input contains NaN, infinity or a value too large for dtype('float64')."
> 
> The error message in console is as follows： Traceback (most recent call last): File "/home/gpu/sunqin/gae/train.py", line 265, in roc_curr1, ap_curr1 = get_roc_score(val_edges, val_edges_false, emb=sess.run(GCN1.z_mean, feed_dict=feed_dict)) File "/home/gpu/sunqin/gae/train.py", line 159, in get_roc_score roc_score = roc_auc_score(labels_all, preds_all) File "/etc/anaconda3/envs/sunqin/lib/python3.9/site-packages/sklearn/metrics/_ranking.py", line 546, in roc_auc_score y_score = check_array(y_score, ensure_2d=False) File "/etc/anaconda3/envs/sunqin/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan") File "/etc/anaconda3/envs/sunqin/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite raise ValueError( ValueError: Input contains NaN, infinity or a value too large for dtype('float64').


I run the demo well. I think maybe the version of your package is too new.
